version: '3.8'

services:
  app:
    # 构建指令
    build:
      # 使用当前目录作为构建上下文
      context: .
      # 指定要使用的 Dockerfile
      dockerfile: Dockerfile
    
    # 卷挂载
    # 将本地的持久化数据目录挂载到容器中，确保数据在容器重启后依然存在
    volumes:
      - ./db/chromadb:/app/db/chromadb
      # 将本地的知识库数据挂载到容器中
      - ./data:/app/data

    # 端口映射
    # 将主机的 8000 端口映射到容器的 8000 端口
    ports:
      - "21145:8000"

    # 环境变量
    # 从项目根目录下的 .env 文件中读取环境变量
    # 这是一种安全的方式来管理敏感信息，如 API 密钥
    env_file:
      - .env

    # 重启策略
    # 除非手动停止，否则容器总是在退出时重新启动
    restart: unless-stopped

    # 容器名称
    container_name: jsontreerag_app

# 注意：
# 1. 运行索引器: 
#    在首次启动或知识库更新后，需要手动运行索引脚本。
#    在终端中执行以下命令:
#    docker-compose run --rm app python scripts/data_indexer.py
#
# 2. 启动API服务:
#    docker-compose up -d
